[package]
name = "msnp11-sdk"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "io-util", "net", "macros", "sync", "time"] }
base64 = "0.22.1"
log = { version = "0.4.27", features = ["std"] }
reqwest = "0.12.15"
quick-xml = { version = "0.37.5", features = ["serialize"] }
serde = { version = "1.0.219", features = ["derive"] }
urlencoding = "2.1.3"
rand = { version = "0.9.1", features = ["thread_rng"] }
guid-create = "0.4.1"
deku = "0.19.1"
sha1_smol = "1.0.1"
